name: CI

on:
  push:
    branches: 
      - prod

jobs:
  run_tests:
    runs-on: ubuntu-latest
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3
      - name: setup the testing server with required packages
        run: |
          sudo apt-get -y upgrade && sudo apt-get -y update && sudo apt-get -y install python3.9
          sudo apt -y install  python3-wheel vim
          export FLASK_APP=flasky.py
          export FLASK_CONFIG=testing
          python3.9 -m pip install -r requirements/common.txt
          python3.9 -m flask test